### ISSUE TITLE
Dec 6: PDL::Finance::TA

### ISSUE THREAD

**Issue by vikasnkumar** [PDLPorters/pdlporters.github.com#28]
Please see the GIST linked here: https://gist.github.com/vikasnkumar/dcfbbce10bc8bb300794896596bb7463

**Comment by duffee** [comment]
Very nice write-up and I appreciate the green and red lights on the final plot ;)

My only suggestion is to link to https://metacpan.org/pod/PDL::Finance::TA and https://metacpan.org/pod/PDL::Graphics::Gnuplot the first time that they're mentioned.

I was just creating placeholders for posts when I saw this. I'd be happy to bump this one up to December 4 or 6 so that people feel they're getting something meaty to chew on for the weekend.

**Comment by vikasnkumar** [comment]
> 
> My only suggestion is to link to https://metacpan.org/pod/PDL::Finance::TA and https://metacpan.org/pod/PDL::Graphics::Gnuplot the first time that they're mentioned.
> 

Thanks for the recommendation @duffee . I have updated the gist to reflect the URLs for PDL, PDL::Finance::TA and PDL::Graphics::Gnuplot.

**Comment by vikasnkumar** [comment]
I made more revisions to the text to fix typos and other errors. now i think it is ready to go.

**Comment by mohawk2** [comment]
How do you folks want to play this? Are you comfortable turning that gist into a PR on this site, using the technique outlined on https://github.com/PDLPorters/pdl/issues/503 ?

**Comment by duffee** [comment]
If @vikasnkumar is busy, I can turn the gist into a PR.  All we need is the name you want as Author, a short bio and a banner image for the top of the post in a separate file with the attribution. Any tags you think are appropriate will help with the SEO.

**Comment by vikasnkumar** [comment]
I can do it today. 

--
  Vikas Kumar
  ***@***.***
